minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.65
neo_version_range=[21.1.0,)
loader_version_range=[4,)

mod_id=enginecore
mod_name=EngineCore
mod_license=Apache-2.0
mod_version=1.0.0
mod_group_id=com.enginecore
mod_authors=Da-Slimy
mod_description=High-performance modular server & client engine optimizer.
